# For more theme config options, see https://github.com/lxndrblz/anatole#modifying-the-configtoml
baseURL = "https://www.jasonyao.com"
languageCode = "en-us"
title = "Home"
theme = "anatole"

# Enables access to SHA and other git information
enableGitInfo = true

# Theme-specific configs
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Adds ability for people to leave comments on posts
disqusShortname = "jasonyao"

[markup]
  [markup.highlight]
    lineNos = true
    noClasses = false

[params]
displayMode = "dark"
title = "Jason Yao"
author = "Jason Yao"
description = "Software engineer, Chaotic-Stupid DnD player, bad shower singer."
profilePicture = "global/profile-church.png"
image = "assets/home/default-hamilton.jpg"
favicon = "assets/favicons/"

# Enables direct embedding of HTML snippets in the markdown files
# [markup.goldmark.renderer]
# unsafe= true

##
# Theme overrides
##
mainSections = ["posts"]

################### DISABLED FOR NOW
# example ["js/custom.js"]
#customJs = []

# Use an empty list if having a custom root page instead of post listings


# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#################### DISABLED FOR NOW

# Swaps the generated URL routes from just the
# title to include publish year/month
[permalinks]
  posts = "posts/:year/:month/:day/:title/"

##
# SEO
##
googleSiteVerify = "bS_JqKuXEPzN-1VZ4w0kc-PhpPeTs-ng8VtsvpnwXCU"

##
# Enables up ability to create static JSON blobs that
#   can be served as a read-only API.
#
# E.g. All posts will now generate an index.json containing
#   the post metadata
##
[outputs]
    page = ["html", "json"]
    section = ["html", "rss", "json"]
    home = ["html", "rss", "json"]

##
# Nav menu
##

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Resume"
  weight = 400
  identifier = "resume"
  url = "/resume/"
