# This is a basic workflow to help you get started with Actions

name: Site Benchmarking

# We only want to run our benchmarks on a new publish
on:
  push:
    branches:
      - publish

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  benchmark:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # No need to deploy site, as the action will run its own server
      #   for more information, see https://github.com/treosh/lighthouse-ci-action#recipes
      #   under the "Test a static site without having to deploy it." section
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v7
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: '.github/workflows/resources/lighthouserc.json'
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
