# This is a basic workflow to help you get started with Actions

name: CI

# We don't want another build triggered from our deployment branch (master in this instance)
on:
  push:
    branches-ignore:
      - publish

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Ruby used for html lint, and node used for json lint
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup lint dependencies
        run: gem install html-proofer && npm install jsonlint -g

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: build site
        run: bin/build

      # Runs a whole bunch of linters for config, generated JSON/html
      - name: validate build
        run: bin/validate

      # The weird github ref thing below just extracts out the branch
      #   name for us, similar to $TRAVIS_BRANCH
      - name: Deploy site
        run: bin/deploy ${GITHUB_REF##*/} ${{secrets.DEPLOYMENT_TOKEN}}

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
